### ISSUE TITLE
Cluster monitoring

### ISSUE THREAD

**Issue by asbjornenge** [wrouesnel/postgres_exporter#128]
Hi!

I'm building out a postgres cluster using `single master replication` and `pgpool`. I'm wondering how to run the exporter for this setup. Should I run one exporter for each replica + master? Also one for pgpool? Also wondering what metrics to monitoring for a cluster setup. What correlates to things like latency, active replicas, load distribution etc.

Any an all help super appreciated 😬 👍

Thanks!

**Comment by wrouesnel** [comment]
Ultimately it depends what you want to monitor. One exporter per postgres instance would be how I'd do it - I suspect pgpool would actually need its own metrics via another system since pointing a postgres_exporter at it would just give you the underlying servers metrics.

Monitoring tuples returned is a good way to get an idea of application load but databases are finicky things so there's a lot more included which with be scraped for you.

**Comment by asbjornenge** [comment]
@wrouesnel thanks a bunch! I'll try that approach initially, and perhaps build out an exporter for pgpool if I see the need 👍
