### ISSUE TITLE
Is one postgres_expoter can connect only one database address?

### ISSUE THREAD

**Issue by gaozhenmin** [wrouesnel/postgres_exporter#180]

**Comment by TattiQ** [comment]
As far as I understood , yes. So e.g. in kubernetes one would need to create a separate deployment with a separate datasource name.

**Comment by jmreicha** [comment]
What happens if both exporters are returning the same fields?  Is there any way to segment the results?  Or would you need to spin up a separate Prometheus for each to dump metrics to?

We have a master and two read slaves and I'm trying to come up with a good solution for getting metrics into Prometheus without overcomplicating things.
