### ISSUE TITLE
Option to not query replication stats

### ISSUE THREAD

**Issue by jcollie** [wrouesnel/postgres_exporter#29]
The databases that I currently monitor do not have replication enabled, so every time Prometheus scrapes the exporter, I get these messages in the logs:

```
Sep 22 20:23:56 svr03.ocjtech.us postgres[11980]: [2-1] ERROR:  relation "pg_replication_slots" does not exist at character 162
Sep 22 20:23:56 svr03.ocjtech.us postgres[11980]: [2-2] STATEMENT:
Sep 22 20:23:56 svr03.ocjtech.us postgres[11980]: [2-3]             SELECT *, pg_current_xlog_location(), pg_xlog_location_diff(pg_current_xlog_location(), replay_location)::float FROM pg_stat_replication
Sep 22 20:23:56 svr03.ocjtech.us postgres[11980]: [2-4]                     INNER JOIN pg_replication_slots ON pg_stat_replication.pid=pg_replication_slots.active_pid
```

It'd be good if there was a command line switch to turn off these queries, it'd be GREAT if the exporter could determine that replication wasn't in use automatically and not issue these queries.

**Comment by wrouesnel** [comment]
This is indeed a problem. The main issue is there's now way for the exporter to know if replication should be enabled or not. I think the fix is just going to be a command line flag "expect-replication" which raises this to the level of error and ignores it otherwise (since I don't want to break backwards compatibility for people using it this way already).

**Comment by draeron** [comment]
i had issue with running the exporter with a aurora rds database (which is compatible with postgres 9.6.8).

This what you'll get in the exporter logs : 
```
Error running query on database:  pg_stat_replication pq: Function pg_stat_get_wal_senders() is currently not supported in Aurora
```

Seems like aurora doesn't expose replication information and honestly we don't really care for those metrics anyway but we do want the other metrics. So i checked out the code and remove everything related `pg_stat_replication`. 

Since this might happen to someone else i though it would be useful to post this here. I could do a proper PR for this if you are interested in this behavior.

**Comment by dbadea-sugarcrm** [comment]
Hi daeron, Please do a PR with your change. I am also interested in this fix
