### ISSUE TITLE
Issues with alerting (when comparing 2 Prometheus queries)

### ISSUE THREAD

**Issue by alasgarov83** [wrouesnel/postgres_exporter#437]
I am facing an issue when trying to set up an alerting, by comparing expressions e.g.: 

**pg_stat_activity_count{namespace="my_namespace"} > pg_settings_max_connections{namespace="my_namespace"} * 0.9**

alerts are not firing as expected. But If I put a digit to compare with, e.g. 

**pg_stat_activity_count{namespace="my_namespace"} > 10** , then it works fine. 

When I execute my queries in prometheus both **pg_stat_activity_count{namespace="my_namespace"}**  and **pg_settings_max_connections{namespace="my_namespace"} * 0.9** separately give valid results. 
So it should work, but for some reason it doesn't. I've tried all possible brackets, quotations whatever, but nothing helps. 
Did anyone encounter a similar issue? Am I missing something here?
Thank you in advance!

Prometheus version:  2.20.1
Postgres version: 10.12

**Comment by frenkye** [comment]
This is due how prometheus work with metrics, basically when you try to use diffrent metrics you need to have same labels on both sides. Which there is not by default because **pg_stat_acitivy_count** return labels as **datname** which aren't in **pg_settings_max_connections**

We have multiple instances and using for each psql separate exporter, which is diversed by our instance label in our usecase. You can manipulate labels via sum() or other PromQL functions. This is what we used for connection usage in percetage.
`round(sum by (instance) (pg_stat_activity_count{instance=~".+"}) / sum by (instance) (pg_settings_max_connections{instance=~".+"}) * 100,0.1) > 85`

Don't just copy paste alerts you see online, you should try them always on prometheus GUI first to see how they behave.

**Comment by alasgarov83** [comment]
@frenkye Thank you very much for your answer, when I was looking at 'pg_stat_activity_count' and 'pg_settings_max_connections' on prometheus I've seen that both contain 'namespace' label, I thought that it will be the joining point (intersection), but it seems like it's not working like that. Yes we also have multiple instances and I've created dedicated exporter for each one of them, that's why using labels is important to create meaningful alerts. 
Your sophisticated query gives a good example, I will try to play around to see if I can adopt it to my environment! 
Thanks again!
