### ISSUE TITLE
Postgres_exporter temiout for a specific query

### ISSUE THREAD

**Issue by mkdel** [wrouesnel/postgres_exporter#462]
hi,
Could not find in manual
 but is it possible to have a specific timeout for a particular metric query?
I have some heavyweight SQL that better to run once in a few minutes.
thanks!

**Comment by wrouesnel** [comment]
At present this is not possible. There is a logical boundary where doing heavy weight SQL via this exporter is starting to defeat the point (since how does Prometheus scrape other metrics more rapidly?)

At the point you have these sorts of delays, you should deploy another exporter (or the custom SQL exporter) and configure a separate job.
